INHERIT: mkdocs-base.yaml

site_name: "Dynatrace Enablement Lab: Kubernetes 101"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-kubernetes-101"
nav:
  - "Welcome": index.md
  - "Prerequisites": prerequisites.md
  - "1. Deploy the Operator": 1-deploy-operator.md
  - "2. Deploy the DynaKube": 2-deploy-dynakube.md
  - "3. Restart Application Services": 3-restart-services.md
  - "Resources": resources.md

extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/f20e348d38e305a8_complete.js"
